name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          # Disable macos build for now since it keeps failing with dune not found
          # - macos-latest
          - ubuntu-latest
        ocaml-version:
          - 4.11.1
          - 4.10.1
          - 4.09.1
          - 4.08.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Retrieve opam cache
        uses: actions/cache@v2
        if: runner.os != 'Windows'
        id: cache-opam
        with:
          path: ~/.opam
          key: v1-${{ runner.os }}-opam-${{ matrix.ocaml-version }}-${{ hashFiles('*.opam.locked') }}
          restore-keys: |
            v2-${{ runner.os }}-opam-${{ matrix.ocaml-version }}-
      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true
      - name: Recover from an Opam broken state
        if: steps.cache-opam.outputs.cache-hit == 'true'
        run: opam upgrade --fixup
      - name: Build
        run: make build
      - name: Run tests
        run: make test
